# Generated by Django 2.2.3 on 2019-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbrand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_1', models.ImageField(help_text='Bag product image', upload_to='bag_product')),
                ('image_2', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_3', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_4', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('image_5', models.ImageField(blank=True, help_text='Bag product image', upload_to='bag_product')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('women', models.BooleanField(default=True)),
                ('new', models.BooleanField(default=True)),
                ('kind', models.CharField(default='bag, belt, jewelry', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image_1', models.ImageField(help_text='Men product image', upload_to='men_product')),
                ('image_2', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_3', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_4', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('image_5', models.ImageField(blank=True, help_text='Men product image', upload_to='men_product')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('new', models.BooleanField(default=True)),
                ('kind', models.CharField(default='jacket, pants, t-short, sweatshirt, dress, shoes', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
